# Fonts included. Not committed to the repository.

# Panton
/panton
    - panton-black-webfont.woff2
    - panton-bold-webfont.woff2
    - panton-light-webfont.woff2
    - panton-regular-webfont.woff2
    - panton-thin-webfont.woff2

# Proxima NNova Soft
/proximasoft
    - proxima-nova-soft-bold-webfont.ttf
    - proxima-nova-soft-regular-webfont.ttf