name: Elysia Deploy

on:
  workflow_call:

jobs:
  elysia-deploy:
    name: 🛩️ Elysia deploy → staging
    runs-on: self-hosted
    env:
      DIR: ${{ secrets.DASH_DIR_DEV }}
    steps:
      - name: Sync api folder
        run: |
          cd "$DIR"
          git fetch origin
          git checkout origin/${{ github.ref_name }} -- api
      - name: Restart api-dev
        run: /home/pollux/polaris/scripts/server-deploy.sh api-dev staging
