name: Deploy Staging

on:
  workflow_call:

jobs:
  pull-staging:
    name: 🔄️ Sync Staging
    runs-on: self-hosted
    env:
      DIR: ${{ secrets.DASH_DIR_DEV }}
    steps:
      - name: Sync repo
        run: |
          cd "$DIR"
          git fetch origin
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # pull the PR head directly
            prref=${{ github.event.pull_request.head.ref }}
            git fetch origin "$prref":"pr-head"
            git reset --hard pr-head
          else
            git reset --hard origin/dev
          fi

  deploy-staging:
    name: 🚀 Deploy → Staging
    runs-on: self-hosted
    needs: pull-staging
    steps:
      - run: /home/pollux/polaris/scripts/server-deploy.sh dashboard staging
